// <auto-generated />
using System;
using GarageApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GarageApp.Migrations
{
    [DbContext(typeof(GarageAppDbContext))]
    partial class GarageAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GarageApp.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarChassisType")
                        .HasColumnType("int");

                    b.Property<Guid>("GarageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GarageId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarChassisType = 0,
                            GarageId = new Guid("b0fcfba8-dedc-4654-9f8d-636b9e19a8d0"),
                            IsAvailable = true,
                            Make = "BMW",
                            Model = "M3",
                            Year = 2021
                        },
                        new
                        {
                            Id = 2,
                            CarChassisType = 9,
                            GarageId = new Guid("7147ac98-3245-4031-9674-2fa1fe564408"),
                            IsAvailable = false,
                            Make = "Audi",
                            Model = "Q7",
                            Year = 2019
                        },
                        new
                        {
                            Id = 3,
                            CarChassisType = 8,
                            GarageId = new Guid("2c2fca1e-ad73-46a1-b4ee-2809f422733f"),
                            IsAvailable = true,
                            Make = "Mazda",
                            Model = "M6",
                            Year = 2022
                        },
                        new
                        {
                            Id = 4,
                            CarChassisType = 2,
                            GarageId = new Guid("b0fcfba8-dedc-4654-9f8d-636b9e19a8d0"),
                            IsAvailable = true,
                            Make = "Toyota",
                            Model = "Corolla",
                            Year = 2020
                        });
                });

            modelBuilder.Entity("GarageApp.Models.Garage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Garages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0fcfba8-dedc-4654-9f8d-636b9e19a8d0"),
                            Location = "Sofia Center",
                            Name = "Downtown Auto Garage"
                        },
                        new
                        {
                            Id = new Guid("7147ac98-3245-4031-9674-2fa1fe564408"),
                            Location = "Plovdiv West",
                            Name = "Westside Performance Garage"
                        },
                        new
                        {
                            Id = new Guid("2c2fca1e-ad73-46a1-b4ee-2809f422733f"),
                            Location = "Varna Industrial Zone",
                            Name = "Mountain View Garage"
                        });
                });

            modelBuilder.Entity("GarageApp.Models.Car", b =>
                {
                    b.HasOne("GarageApp.Models.Garage", "Garage")
                        .WithMany("Cars")
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garage");
                });

            modelBuilder.Entity("GarageApp.Models.Garage", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
